server:
  host: "127.0.0.1"
  port: 32001
  mcp_path: "/data/api/mcp"

cache:
  enabled: true
  ttl: 3600
  type: "memory"

backend:
#  chatgpt_service_url: "http://chatgpt-api-service:31001"
#  chatdb_service_url: "http://chatdb-visual-service:31001"
#  workflow_service_url: "http://llm-workflow-service:31001"
  chatgpt_service_url: "http://chatgpt-api-service:31001"
  chatdb_service_url: "http://chatdb-visual-service:31001"
  workflow_service_url: "http://llm-workflow-service:31001"

  timeout: 30

logging:
  level: "INFO"
